### ISSUE TITLE
希望能够继续更新

### ISSUE THREAD

**Issue by VimWei** [RodenLuo/py4e-cn#5]
希望能够继续更新

**Comment by RodenLuo** [comment]
好的，我看情況。当年很热血，后来遇到了很多事情和一些波折，就搁置了。也欢迎大家一起翻译。

如果在自己学习Python的话，前几天李笑来刚刚开源了[一本书](https://github.com/selfteaching/the-craft-of-selfteaching)，非常不错，可以考虑跟一下。

**Comment by RodenLuo** [comment]
即将重启翻译，欢迎提供反馈
